[build.environment]
NPM_FLAGS = "--version"

[build]
command = "npx pnpm@7 i --store=node_modules/.pnpm-store && npx pnpm@7 run build"
ignore = "git diff --quiet HEAD^ HEAD src index.html"
publish = "dist"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"
